CREATE TABLE [dbo].[CAT_ROLE]
(
	[ROL_INT_ID] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(), 
    [ROL_NAME] VARCHAR(50) NULL, 
    CONSTRAINT [FK_CAT_ROLE_TBL_USER] FOREIGN KEY (ROL_INT_ID) REFERENCES TBL_USER([USE_INT_ID])
)
