CREATE TABLE [dbo].[CAT_CATEGORIA] (
    [CAT_INT_ID]   UNIQUEIDENTIFIER CONSTRAINT [DF_CAT_CATEGORIA_CAT_INT_ID] DEFAULT (newid()) NOT NULL PRIMARY KEY,
    [CAT_NOMBRE]   VARCHAR (50)     NULL,
    [CAT_SYS_NAME] VARCHAR (50)     NULL,
    [CAT_STATUS]   BIT              NULL
);

