CREATE TABLE [dbo].[CAT_PROVEEDOR] (
    [PROV_INT_ID]    UNIQUEIDENTIFIER CONSTRAINT [DF_CAT_PROVEEDOR_PROV_INT_ID] DEFAULT (newid()) NOT NULL,
    [PROV_PRIMER_N]  VARCHAR (100)    NULL,
    [PROV_SEGUNDO_N] VARCHAR (100)    NULL,
    [PROV_PRIMER_A]  VARCHAR (50)     NULL,
    [PROV_SEGUNDO_A] VARCHAR (50)     NULL,
    [PROV_FECHA_NAC] DATE             NULL,
    [PROV_CEL]       VARCHAR (50)     NULL,
    [PROV_TEL]       VARCHAR (50)     NULL
);

