CREATE TABLE [dbo].[TBL_PRODUCTO] (
    [PROD_INT_ID]   UNIQUEIDENTIFIER DEFAULT (newid()) NOT NULL  PRIMARY KEY,
    [PROD_NOMBRE]   VARCHAR (100)    NULL,
    [PROD_STATUS]   BIT              NULL,
    [PROD_SYS_NAME] VARCHAR (50)     NULL,
    [PROD_PRE_V]    DECIMAL (18, 2)  NULL,
    [PROD_PRE_C]    DECIMAL (18, 2)  NULL,
    [PROD_CANT]     INT              NULL,
    [CAT_INT_ID]    UNIQUEIDENTIFIER NOT NULL,
    [USE_INF_INT_ID]   UNIQUEIDENTIFIER DEFAULT (newid()) NOT NULL,
	CONSTRAINT [FK_TBL_PRODUCTO]  FOREIGN KEY ([CAT_INT_ID]) REFERENCES [dbo].[CAT_CATEGORIA] ([CAT_INT_ID])
);

