CREATE TABLE [dbo].[TBL_PRODUCTO] (
    [PROD_INT_ID]   UNIQUEIDENTIFIER CONSTRAINT [DF_TBL_PRODUCTO_PROD_INT_ID] DEFAULT (newid()) NULL,
    [PROD_NOMBRE]   VARCHAR (100)    NULL,
    [PROD_STATUS]   BIT              NULL,
    [PROD_SYS_NAME] VARCHAR (50)     NULL,
    [PROD_PRE_V]    DECIMAL (18, 2)  NULL,
    [PROD_PRE_C]    DECIMAL (18, 2)  NULL,
    [PROD_CANT]     INT              NULL,
    [CAT_INT_ID]    UNIQUEIDENTIFIER NULL,
    [PROV_INT_ID]   UNIQUEIDENTIFIER NULL
);

