CREATE TABLE [dbo].[TBL_USER_INFO] (
    [USE_INF_INT_ID]   UNIQUEIDENTIFIER DEFAULT (newid()) NOT NULL,
	CAT_TYP_USER       UNIQUEIDENTIFIER DEFAULT (newid()) NOT NULL,
    [USE_INF_PRIMER_N]  VARCHAR (100)    NULL,
    [USE_INF_SEGUNDO_N] VARCHAR (100)    NULL,
    [USE_INF_PRIMER_A]  VARCHAR (50)     NULL,
    [USE_INF_SEGUNDO_A] VARCHAR (50)     NULL,
    [USE_INF_FECHA_NAC] DATE             NULL,
    [USE_INF_CEL]       VARCHAR (50)     NULL,
    [USE_INF_TEL]       VARCHAR (50)     NULL,
    [USE_INF_EMAIL]            VARCHAR (100)    NULL,
    PRIMARY KEY CLUSTERED ([USE_INF_INT_ID] ASC),
   
);

