CREATE TABLE [dbo].[TBL_USER_INFO] (
    [USE_INF_INT_ID]   UNIQUEIDENTIFIER DEFAULT (newid()) NOT NULL,
    [USE_INT_ID]       UNIQUEIDENTIFIER DEFAULT (newid()) NOT NULL,
    [USE_INF_APELLIDO] VARCHAR (100)    NULL,
    [USE_INF_EMAIL]            VARCHAR (100)    NULL,
    [USE_INF_FECHA_NAC] DATE NULL, 
    PRIMARY KEY CLUSTERED ([USE_INF_INT_ID] ASC),
    CONSTRAINT [FK_TBL_USER_INFO_TBL_USER] FOREIGN KEY ([USE_INT_ID]) REFERENCES [dbo].[TBL_USER] ([USE_INT_ID])
);

