CREATE TABLE [dbo].[TBL_USER] (
    [USE_INT_ID]  UNIQUEIDENTIFIER DEFAULT (NEWID()) NOT NULL,
	[USE_INF_INT_ID]   UNIQUEIDENTIFIER DEFAULT (newid()) NOT NULL,
    [USE_NAME]  VARCHAR (100)    NULL,
    [USE_LOGIN] VARCHAR (100)    NULL,
    [USE_PASS]  VARCHAR (300)    NULL,
    [ROL_INT_ID] UNIQUEIDENTIFIER NULL DEFAULT (NEWID()), 
    [USE_STATUS] BIT NULL, 
    PRIMARY KEY CLUSTERED ([USE_INT_ID]  ASC),
	CONSTRAINT [FK_TBL_USER] FOREIGN KEY ([USE_INT_ID]) REFERENCES [dbo].[TBL_USER_INFO] ([USE_INF_INT_ID])

);

