CREATE TABLE [dbo].[TBL_USER] (
    [USE_INT_ID]  UNIQUEIDENTIFIER DEFAULT (NEWID()) NOT NULL,
    [USE_NAME]  VARCHAR (100)    NULL,
    [USE_LOGIN] VARCHAR (100)    NULL,
    [USE_PASS]  VARCHAR (300)    NULL,
    [ROL_INT_ID] UNIQUEIDENTIFIER NULL DEFAULT (NEWID()), 
    PRIMARY KEY CLUSTERED ([USE_INT_ID]  ASC)
);

