CREATE TABLE [dbo].[TBL_USER] (
    [USEINTID]  UNIQUEIDENTIFIER DEFAULT (newid()) NOT NULL,
    [USE_NAME]  VARCHAR (100)    NULL,
    [USE_LOGIN] VARCHAR (100)    NULL,
    [USE_PASS]  VARCHAR (300)    NULL,
    PRIMARY KEY CLUSTERED ([USEINTID] ASC)
);

